os: linux
dist: xenial
sudo: required
language: c
before_install:
  - wget https://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en603996 -O atmel_toolchain.tar.gz
install:
  - pyenv local 3.7
  - pip3 install --user -r tools/requirements.txt
  - tar -zxf atmel_toolchain.tar.gz
  - export PATH="$PATH:$TRAVIS_BUILD_DIR/arm-none-eabi/bin"
  - python3 -m tools.generate_makefile
script:
  - make all
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./tools/commit_firmware.sh; fi
  - if [ "$TRAVIS_BRANCH" = "maintenance-v1" ]; then ./tools/commit_firmware.sh; fi
notifications:
  slack: revolution-robotics:sXlaetqFuXuT3Vr4atwogEdK
