#ifndef COMPONENT_WATCHDOG_FEEDER_H_
#define COMPONENT_WATCHDOG_FEEDER_H_

#ifndef COMPONENT_TYPES_WATCHDOG_FEEDER_H_
#define COMPONENT_TYPES_WATCHDOG_FEEDER_H_



#endif /* COMPONENT_TYPES_WATCHDOG_FEEDER_H_ */

void WatchdogFeeder_Run_Feed(void);

#endif /* COMPONENT_WATCHDOG_FEEDER_H_ */
